server:
  port: ${PORT:8181}
  cors:
    enabled: true
  servlet:
    context-path: /finco

springdoc:
  swagger-ui:
    path: /

router:
  static-resources:
    default:
        enabled: true
        mapping: /views/**
        paths: classpath:views
    swagger:
        paths: classpath:META-INF/swagger
        mapping: ${app.api.swagger.path}/**
    web:
        paths: classpath:web
        mapping: /**

nlp:
  url: ${NLP_URL:http://localhost:5000}

dist:
  url: ${DISTR_URL:http://rapport-integration.australiaeast.cloudapp.azure.com}
  bearer: ${BEARER_TOKEN:eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0UjF5Z0daNzZSTkl4ZFNZNzc2STdtNTNXUWpuaEJJRDRGUDB0UnVtVHkwIn0.eyJleHAiOjE2NjI4ODI0MzYsImlhdCI6MTY2Mjg4MjEzNiwiYXV0aF90aW1lIjoxNjYyODgyMTA2LCJqdGkiOiI0MGZiZjdlYS05NDcxLTQzZmYtYWIxYS1hZTkxYWQ3MTllNjMiLCJpc3MiOiJodHRwOi8vcmFwcG9ydC1pbnRlZ3JhdGlvbi5hdXN0cmFsaWFlYXN0LmNsb3VkYXBwLmF6dXJlLmNvbS9hdXRoL3JlYWxtcy9yYXBwb3J0IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImFhNTQ0ODE1LTJmY2UtNDlmNS1hNzYzLTg1OWJmYzFiN2E2OCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRpc3RyaWJ1dGlvbnMiLCJub25jZSI6Ilh6aEpkRFI1TmxVdFUwMW1hVUYxTVZwa0xrNXdhazlNUWxOLWNURnVURUpFT0RCZlFqVXdWRGRwVlROMiIsInNlc3Npb25fc3RhdGUiOiJkOTZkMGY4OC0wZDZmLTRhZWQtODc1Mi02MmNlNGQ2MDJmMzQiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9yYXBwb3J0LWludGVncmF0aW9uLmF1c3RyYWxpYWVhc3QuY2xvdWRhcHAuYXp1cmUuY29tLyoiLCJodHRwOi8vcmFwcG9ydC1pbnRlZ3JhdGlvbi5hdXN0cmFsaWFlYXN0LmNsb3VkYXBwLmF6dXJlLmNvbTo4MC8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1yYXBwb3J0Il19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGlzdHJpYnV0aW9ucyI6eyJyb2xlcyI6WyJHdXJ1Il19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIG9mZmxpbmVfYWNjZXNzIGVtYWlsIiwic2lkIjoiZDk2ZDBmODgtMGQ2Zi00YWVkLTg3NTItNjJjZTRkNjAyZjM0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRGlzdHJpYnV0aW9ucyBHdXJ1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGlzdHJpYnV0aW9ucy5ndXJ1IiwiZ2l2ZW5fbmFtZSI6IkRpc3RyaWJ1dGlvbnMiLCJmYW1pbHlfbmFtZSI6Ikd1cnUifQ.gvPqYfdHeQBt-Gp_qPNCtIdsG59lsyYHUMtUkiw5w28MY40tJet1TtUtOrs5GafXa5c1WyZydFyzgguSS-6V2cuXlsMOfUvYrEDIwdyaiJFMfQvPJYKX3tOlbv0vlVt1pu-TgD8MHWvgkFQLDJq6Oj6-oxMY9bgMVrwglgaeAt0C0Y_hYT-sBWOuCKItORWs8hT7tbBbFc8yshUr3d0xZOpfOQaGGtPzFDebxi6EMfMAGVfasG5AzDDC_PiNneOB-CQUI0-AL4gTdXgVOQ6-ejEMx5iIcaE3JWL9--H6ynao4hWd_j9CiPqVM63wHrYPf3A7QQji2HBWdcRj509WTA}
