server:
  port: ${PORT:8181}
  cors:
    enabled: true
  servlet:
    context-path: /finco

springdoc:
  swagger-ui:
    path: /

router:
  static-resources:
    default:
        enabled: true
        mapping: /views/**
        paths: classpath:views
    swagger:
        paths: classpath:META-INF/swagger
        mapping: ${app.api.swagger.path}/**
    web:
        paths: classpath:web
        mapping: /**

nlp:
  url: ${NLP_URL:http://localhost:5000}
