server:
  port: ${PORT:8181}
  cors:
    enabled: true
  servlet:
    context-path: /finco

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/finco-db
    username: postgres
    password: password # Write password as you want
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


springdoc:
  swagger-ui:
    path: /

router:
  static-resources:
    default:
        enabled: true
        mapping: /views/**
        paths: classpath:views
    swagger:
        paths: classpath:META-INF/swagger
        mapping: ${app.api.swagger.path}/**
    web:
        paths: classpath:web
        mapping: /**

nlp:
  url: ${NLP_URL:http://localhost:5000}

sonata:
  url: ${SBS_URL:http://localhost:8080/sonata/rest/sbs}

nucleus:
  url: ${NUCLEUS_URL:http://localhost:8080/components/api}

dist:
  url: ${DSTR_URL:http://localhost:8080/distributions/api}
  bearer_uri: ${BEARER_URI:http://localhost:8080/distributions/api/oidc/oauth2/token?username=p2gupta@bravurasolutions.com&password=dstr@12345&}
