server:
  port: ${PORT:8181}
  cors:
    enabled: true
  servlet:
    context-path: /finco


springdoc:
  swagger-ui:
    path: /

router:
  static-resources:
    default:
        enabled: true
        mapping: /views/**
        paths: classpath:views
    swagger:
        paths: classpath:META-INF/swagger
        mapping: ${app.api.swagger.path}/**
    web:
        paths: classpath:web
        mapping: /**

nlp:
  url: ${NLP_URL:http://localhost:5000}

sonata:
  url: ${SBS_URL:http://localhost:8080/sonata/rest/sbs}

nucleus:
  url: ${NUCLEUS_URL:http://localhost:8080/components/api}

dist:
  url: ${DSTR_URL:http://localhost:8080/distributions/api}
  bearer_uri: ${BEARER_URI:http://localhost:8080/distributions/api/oidc/oauth2/token?username=p2gupta@bravurasolutions.com&password=dstr@12345&}
