server:
  port: ${PORT:8181}
  cors:
    enabled: true
  servlet:
    context-path: /finco

springdoc:
  swagger-ui:
    path: /

router:
  static-resources:
    default:
        enabled: true
        mapping: /views/**
        paths: classpath:views
    swagger:
        paths: classpath:META-INF/swagger
        mapping: ${app.api.swagger.path}/**
    web:
        paths: classpath:web
        mapping: /**

nlp:
  url: ${NLP_URL:http://localhost:5000}

dist:
  url: ${DSTR_URL:http://rapport-integration.australiaeast.cloudapp.azure.com/distributions/api}
  bearer: ${BEARER_TOKEN:eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0UjF5Z0daNzZSTkl4ZFNZNzc2STdtNTNXUWpuaEJJRDRGUDB0UnVtVHkwIn0.eyJleHAiOjE2NjI5MTg4NzMsImlhdCI6MTY2MjkxODU3MywiYXV0aF90aW1lIjoxNjYyOTE4NTY1LCJqdGkiOiIxZDRhY2Q0ZS1kZjMyLTRkMzEtYWYxMC04NDAxOTRkYmQyYmEiLCJpc3MiOiJodHRwOi8vcmFwcG9ydC1pbnRlZ3JhdGlvbi5hdXN0cmFsaWFlYXN0LmNsb3VkYXBwLmF6dXJlLmNvbS9hdXRoL3JlYWxtcy9yYXBwb3J0IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImFhNTQ0ODE1LTJmY2UtNDlmNS1hNzYzLTg1OWJmYzFiN2E2OCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRpc3RyaWJ1dGlvbnMiLCJub25jZSI6IlpDMU1USE5oU2xSWU1UVXVZbXBKVDNGZmJHazJURWR0VVhJMmNWTmxXa2wxZDA1T2JIQldabWs1Y21WZiIsInNlc3Npb25fc3RhdGUiOiIyODkwNTdjMy00NTM2LTQwODEtYjg4My1hZDM1MTJkOWJmZmQiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9yYXBwb3J0LWludGVncmF0aW9uLmF1c3RyYWxpYWVhc3QuY2xvdWRhcHAuYXp1cmUuY29tLyoiLCJodHRwOi8vcmFwcG9ydC1pbnRlZ3JhdGlvbi5hdXN0cmFsaWFlYXN0LmNsb3VkYXBwLmF6dXJlLmNvbTo4MC8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1yYXBwb3J0Il19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGlzdHJpYnV0aW9ucyI6eyJyb2xlcyI6WyJHdXJ1Il19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIG9mZmxpbmVfYWNjZXNzIGVtYWlsIiwic2lkIjoiMjg5MDU3YzMtNDUzNi00MDgxLWI4ODMtYWQzNTEyZDliZmZkIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRGlzdHJpYnV0aW9ucyBHdXJ1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGlzdHJpYnV0aW9ucy5ndXJ1IiwiZ2l2ZW5fbmFtZSI6IkRpc3RyaWJ1dGlvbnMiLCJmYW1pbHlfbmFtZSI6Ikd1cnUifQ.IY2IaT3N1c0n55Wuf8O81gLW4sEHyfMUeJ1eMjOICXw_CK6vrROVAaQa1QaLcmDQoeak1j9rCQ-n3763O3mstZs9QSN1ERYFTifCT8q4fk9Q4ktUOmVXJuOAokFvjsmSTCXzdsKrBYKdq83pqPGqVfN3fmKaMG_E_72dTQPn9vKduqV_4n7FLZ-ExymUO9AxpE16y2bjNL0GJGHxx9rDCe46gh1j685hwrkX-7zg1lhmFGOKPlnLJeBCYXy69MTIHbiVCGKsfDjPCx3luRIZaHBbYPU88w36IRaA93g6bAdGWoa3Bzrpihg-FeR4wHVE7WrPCVvPSpLbps9kcyXCFQ}
