openapi: 3.0.3
info:
  title: Finco - NLP 1.0
  description: |-
    This NLP does emtity mapping of unstructured text
    
    Some useful links:
    - [NLP](https://en.wikipedia.org/wiki/Natural_language_processing)
    - [Named Entity Recognition](https://en.wikipedia.org/wiki/Named-entity_recognition)
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://127.0.0.1:5000/
paths:
  /nlp/predict:
    post:
      tags:
        - Finco-NLP NER Endpoint
      summary: Send a string to process
      operationId: genString
      parameters:
        - name: text
          in: query
          description: Text that need to be processed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  paths:
  /intent/predict:
    post:
      tags:
        - Finco-NLP Intent Endpoint
      summary: Send a string to process
      operationId: genString
      parameters:
        - name: text
          in: query
          description: Text that need to be processed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
    
    